# Bibliotecas

In [176]:
from utils import carregar_dados, preprocessar
from genetic import algoritmo_genetico

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    recall_score,
    precision_score,
    roc_auc_score
)

import numpy as np
import pandas as pd

Carregar Dados

In [177]:
df = carregar_dados()
X_tr, X_te, y_tr, y_te = preprocessar(df)

Parametros

In [178]:
GA_CONFIG = {
    "pop_size": 20,
    "generations": 8,
    "mutation_rate": 0.40,
    "tournament_size": 4,
    "penalizacao": 0.04
}

baseline

In [179]:
resultados = []

In [180]:
for i in range(10):

    best_ind, score = algoritmo_genetico(
        X_tr, y_tr, X_te, y_te, GA_CONFIG
    )

    # seleção de features
    X_tr_sel = X_tr[:, best_ind == 1]
    X_te_sel = X_te[:, best_ind == 1]

    # modelo final
    model = GaussianNB()
    model.fit(X_tr_sel, y_tr)

    pred = model.predict(X_te_sel)

    # métricas
    acc = accuracy_score(y_te, pred)

    f1 = f1_score(y_te, pred, average=None)
    recall = recall_score(y_te, pred, average=None)
    precision = precision_score(y_te, pred, average=None)

    auc = roc_auc_score(y_te, pred)

    resultados.append([
        i + 1,
        acc,
        recall[1],
        precision[1],
        f1[1],
        recall[0],
        precision[0],
        f1[0],
        auc,
        np.sum(best_ind),
        len(X_tr_sel)
    ])

Resultados

In [181]:
colunas = [
    "Execução",
    "Acc",
    "R+",
    "P+",
    "F1+",
    "R-",
    "P-",
    "F1-",
    "AUC-ROC",
    "Variáveis",
    "Instâncias de Treinamento"
]

df_resultados = pd.DataFrame(resultados, columns=colunas)

df_resultados

,Execução,Acc,R+,P+,F1+,R-,P-,F1-,AUC-ROC,Variáveis,Instâncias de Treinamento
0,1,0.729730,0.555556,0.454545,0.500000,0.785714,0.846154,0.814815,0.670635,53,440
1,2,0.774775,0.592593,0.533333,0.561404,0.833333,0.864198,0.848485,0.712963,51,440
2,3,0.765766,0.592593,0.516129,0.551724,0.821429,0.862500,0.841463,0.707011,46,440
3,4,0.513514,0.925926,0.324675,0.480769,0.380952,0.941176,0.542373,0.653439,48,440
4,5,0.612613,0.851852,0.370968,0.516854,0.535714,0.918367,0.676692,0.693783,49,440
5,6,0.720721,0.518519,0.437500,0.474576,0.785714,0.835443,0.809816,0.652116,50,440
6,7,0.792793,0.666667,0.562500,0.610169,0.833333,0.886076,0.858896,0.750000,53,440
7,8,0.810811,0.666667,0.600000,0.631579,0.857143,0.888889,0.872727,0.761905,56,440
8,9,0.594595,0.814815,0.354839,0.494382,0.523810,0.897959,0.661654,0.669312,50,440
9,10,0.756757,0.555556,0.500000,0.526316,0.821429,0.851852,0.836364,0.688492,49,440

Estatísticas

In [182]:
df_resultados.describe()

,Execução,Acc,R+,P+,F1+,R-,P-,F1-,AUC-ROC,Variáveis,Instâncias de Treinamento
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.0
mean,5.50000,0.707207,0.674074,0.465449,0.534777,0.717857,0.879261,0.776328,0.695966,50.500000,440.0
std,3.02765,0.099076,0.141626,0.092959,0.053568,0.170316,0.033544,0.110342,0.037746,2.877113,0.0
min,1.00000,0.513514,0.518519,0.324675,0.474576,0.380952,0.835443,0.542373,0.652116,46.000000,440.0
25%,3.25000,0.639640,0.564815,0.387601,0.495787,0.598214,0.854514,0.709973,0.669643,49.000000,440.0
50%,5.50000,0.743243,0.629630,0.477273,0.521585,0.803571,0.875137,0.825589,0.691138,50.000000,440.0
75%,7.75000,0.772523,0.777778,0.529032,0.558984,0.830357,0.895692,0.846729,0.711475,52.500000,440.0
max,10.00000,0.810811,0.925926,0.600000,0.631579,0.857143,0.941176,0.872727,0.761905,56.000000,440.0

media final

In [183]:
df_resultados.mean(numeric_only=True)

Execução                       5.500000
Acc                            0.707207
R+                             0.674074
P+                             0.465449
F1+                            0.534777
R-                             0.717857
P-                             0.879261
F1-                            0.776328
AUC-ROC                        0.695966
Variáveis                     50.500000
Instâncias de Treinamento    440.000000
dtype: float64