# Bibliotecas

In [15]:
from utils import carregar_dados, preprocessar
from genetic import algoritmo_genetico

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    recall_score,
    precision_score,
    roc_auc_score
)

import numpy as np
import pandas as pd

Carregar Dados

In [16]:
df = carregar_dados()
X_tr, X_te, y_tr, y_te = preprocessar(df)

Parametros

In [17]:
GA_CONFIG = {
    "pop_size": 50,
    "generations": 80,
    "mutation_rate": 0.1,
    "tournament_size": 3,
    "penalizacao": 0.01
}

baseline

In [18]:
resultados = []

In [19]:
for i in range(1):

    best_ind, score = algoritmo_genetico(
        X_tr, y_tr, X_te, y_te, GA_CONFIG
    )

    # seleção de features
    X_tr_sel = X_tr[:, best_ind == 1]
    X_te_sel = X_te[:, best_ind == 1]

    # modelo final
    model = GaussianNB()
    model.fit(X_tr_sel, y_tr)

    pred = model.predict(X_te_sel)

    # métricas
    acc = accuracy_score(y_te, pred)

    f1 = f1_score(y_te, pred, average=None)
    recall = recall_score(y_te, pred, average=None)
    precision = precision_score(y_te, pred, average=None)

    auc = roc_auc_score(y_te, pred)

    resultados.append([
        i + 1,
        acc,
        recall[1],
        precision[1],
        f1[1],
        recall[0],
        precision[0],
        f1[0],
        auc,
        np.sum(best_ind),
        len(X_tr_sel)
    ])

Resultados

In [20]:
colunas = [
    "Execução",
    "Acc",
    "R+",
    "P+",
    "F1+",
    "R-",
    "P-",
    "F1-",
    "AUC-ROC",
    "Variáveis",
    "Instâncias de Treinamento"
]

df_resultados = pd.DataFrame(resultados, columns=colunas)

df_resultados

,Execução,Acc,R+,P+,F1+,R-,P-,F1-,AUC-ROC,Variáveis,Instâncias de Treinamento
0,1,0.810811,0.703704,0.593750,0.644068,0.845238,0.898734,0.871166,0.774471,35,440
1,2,0.783784,0.703704,0.542857,0.612903,0.809524,0.894737,0.850000,0.756614,33,440
2,3,0.801802,0.592593,0.592593,0.592593,0.869048,0.869048,0.869048,0.730820,36,440
3,4,0.792793,0.666667,0.562500,0.610169,0.833333,0.886076,0.858896,0.750000,37,440
4,5,0.801802,0.666667,0.580645,0.620690,0.845238,0.887500,0.865854,0.755952,39,440
5,6,0.819820,0.740741,0.606061,0.666667,0.845238,0.910256,0.876543,0.792989,42,440
6,7,0.801802,0.666667,0.580645,0.620690,0.845238,0.887500,0.865854,0.755952,40,440
7,8,0.792793,0.592593,0.571429,0.581818,0.857143,0.867470,0.862275,0.724868,36,440
8,9,0.828829,0.629630,0.653846,0.641509,0.892857,0.882353,0.887574,0.761243,45,440
9,10,0.801802,0.666667,0.580645,0.620690,0.845238,0.887500,0.865854,0.755952,39,440

Estatísticas

In [21]:
df_resultados.describe()

,Execução,Acc,R+,P+,F1+,R-,P-,F1-,AUC-ROC,Variáveis,Instâncias de Treinamento
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.0
mean,5.50000,0.803604,0.662963,0.586497,0.621180,0.848810,0.887117,0.867306,0.755886,38.200000,440.0
std,3.02765,0.013295,0.047655,0.029474,0.024862,0.021771,0.012759,0.010088,0.019369,3.552777,0.0
min,1.00000,0.783784,0.592593,0.542857,0.581818,0.809524,0.867470,0.850000,0.724868,33.000000,440.0
25%,3.25000,0.795045,0.638889,0.573733,0.610853,0.845238,0.883284,0.863170,0.751488,36.000000,440.0
50%,5.50000,0.801802,0.666667,0.580645,0.620690,0.845238,0.887500,0.865854,0.755952,38.000000,440.0
75%,7.75000,0.808559,0.694444,0.593461,0.636304,0.854167,0.892928,0.870636,0.760086,39.750000,440.0
max,10.00000,0.828829,0.740741,0.653846,0.666667,0.892857,0.910256,0.887574,0.792989,45.000000,440.0

media final

In [22]:
df_resultados.mean(numeric_only=True)

Execução                       5.500000
Acc                            0.803604
R+                             0.662963
P+                             0.586497
F1+                            0.621180
R-                             0.848810
P-                             0.887117
F1-                            0.867306
AUC-ROC                        0.755886
Variáveis                     38.200000
Instâncias de Treinamento    440.000000
dtype: float64